[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"
